### ISSUE TITLE
📎 Lower supported Node version

### ISSUE THREAD

**Issue by sebmck** [romefrontend/rome#1001]
VS Code ships with an older version of Node that we only noticed yesterday does not support `recursive` on `rmdir`. We can lower it again once that has been shimmed since it seems like the only version-specific thing in the 12.0 range we are relying on.

**Comment by ljharb** [comment]
Adding the `mkdirp` package should give you pretty far backwards compatibility.

**Comment by sebmck** [comment]
`mkdirp` isn't about to be our first dependency 😛 All `fs` calls go through the `internal/fs/index.ts` module so it's all centralized.

**Comment by sebmck** [comment]
Lowered minimum supported Node version to 12.8 in 38ef4175b0835b1617f952d2d84d7962b0c8a92a and #1001.
