### ISSUE TITLE
A great proposal here, indeed! :tada:

### ISSUE THREAD

**Issue by yufizan** [romefrontend/rome#1025]
A great proposal here, indeed! :tada:

I've taken a look at the related issues mentioned along with the discussions and I've got some questions (probably related):

- Would those disallowed words be fixed or could they be provided/extended?

- I'm not sure if this is supposed to be a zero-config tool, but would you consider adding this as a global suppression through a config file?

It's also worthy to mention it could not only be related to frontend code. You could receive a disallowed word from backend and you kind of must keep using it:

```javascript
const { data } = axios.get('...');
const { blacklist } = data; // would it suggest to rename the `blacklist` identifier?
filter(blacklist);
render(blacklist);
```

You could also rename it to look better, but you still need to make a reference to the disallowed word:

```javascript
const { data } = axios.get('...');
const { blacklist: denylist } = data;
filter(denylist);
render(denylist);
```

_Originally posted by @richardaum in https://github.com/romefrontend/rome/issues/793#issuecomment-671578138_

**Comment by richard-lopes-ifood** [comment]
I didn't get why is it becoming a separate issue?
