### ISSUE TITLE
I'd agree with the Prettier decision by moving the comment inside the `else` block because you could have a lot of comment lines (or a large comment block) - it could hurt the legibility where you could quickly identify if it is about an `if`/`else` statement and not a solely `if`.

### ISSUE THREAD

**Issue by yufizan** [romefrontend/rome#1026]
I'd agree with the Prettier decision by moving the comment inside the `else` block because you could have a lot of comment lines (or a large comment block) - it could hurt the legibility where you could quickly identify if it is about an `if`/`else` statement and not a solely `if`.

```javascript
  // comment for if block
  if (cond1) {
    doFoo(tree, data);
    if (cond2) {
      collect(tree.left, data, depth + 1);
      collect(tree.right, data, depth + 1);
    }
  }
  // what if you 
  // have a lot of comments lines 
  // here
  // it's easy to forget this is about
  // an if/else statement.
  // moving the comment lines to the inside of the else
  // statement quickly reveals
  // what is it about.
  else {
    doBar(data);
  }
```

_Originally posted by @richard-lopes-ifood in https://github.com/romefrontend/rome/issues/1024#issuecomment-671622010_

**Comment by richardaum** [comment]
Didn't get why you keep opening my comments as a new issue. Could you explain it?
