### ISSUE TITLE
Vscode extension crashes after detecting Node version wrongly.

### ISSUE THREAD

**Issue by decafbad** [romefrontend/rome#1028]
## Environment

[mkose@casper units]$ yarn rome rage --summary
yarn run v1.22.4
$ /home/mkose/Desktop/units/node_modules/.bin/rome rage --summary
Environment Variables
  Object {
    COLORTERM: "truecolor"
    LANG: "en_US.UTF-8"
    PATH: "/tmp/yarn--1597112087653-0.13461780193441975:/home/mkose/Desktop/units/node_modu
    les/.bin:/home/mkose/.config/yarn/link/node_modules/.bin:/usr/libexec/lib/node_modules/
    npm/bin/node-gyp-bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/bin/node_modules/n
    pm/bin/node-gyp-bin:/home/mkose/.yarn/bin:/home/mkose/.local/bin:/home/mkose/bin:/usr/l
    ocal/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin"
    TERM: "xterm-256color"
    USER: "mkose"
  }

User Config
  unset

Rome Version
  10.0.3-beta

Node Version
  12.18.3

Platform
  linux x64 5.7.12-200.fc32.x86_64

Terminal Features
  Object {
    background: "unknown"
    colorDepth: 24
    columns: 95
    cursor: true
    hyperlinks: true
    isTTY: true
    unicode: true
  }

Client Flags
  Object {
    clientName: "cli"
    cwd: "/home/mkose/Desktop/units"
    realCwd: "/home/mkose/Desktop/units"
    silent: false
  }

Server Status
  Object {
    projects: Array [
      Object {id: 0}
      Object {id: 1}
    ]
    server: Object {
      heapTotal: 26_050_560
      pid: 11_018
      uptime: 0.223813996
    }
    workers: Array [
      Object {
        astCacheSize: 0
        heapTotal: 26_050_560
        ownedBytes: 0
        ownedFileCount: 0
        pid: 11_018
        uptime: 0.223731714
      }
    ]
  }

## Steps To Reproduce

1. Startl VS Code extension or give VS Code a "reload window" command
2.  Fails with this message: 

Discovered Rome path /home/mkose/Desktop/units/node_modules/rome/bin/rome/index.js
/* then five times: */
Connection to server got closed. Server will restart.
× Node >=12.10.0 is required, but you are on v12.8.1

## Expected Results

It should work because I have Node v12.18.3

**Comment by sebmck** [comment]
The error is correct, the Node version is 12.8.1, it's the Node version inside of VSCode. We've since lowered the supported Node version to resolve it. See #1001 for more info, fixed in #1027.
