### ISSUE TITLE
💭 usage of Record<Keys,Type> to define Dict from "@internal/typescript-helpers"

### ISSUE THREAD

**Issue by flowHater** [romefrontend/rome#1046]
From: https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeystype

Dict should be implemented as:

```typescript
export type Dict<T> = Record<string, T>;
```
Small change to make code more idiomatic.

**Comment by pizzafox** [comment]
Relevant code:

https://github.com/romefrontend/rome/blob/d4ff4dc26129ba0172600fb95c2ba68f9a995ab7/internal/typescript-helpers/index.ts#L27-L29
