### ISSUE TITLE
💭 Add linter rules to detect non-inclusive terminology

### ISSUE THREAD

**Issue by sesm** [romefrontend/rome#1056]
As stated in [Project Philosophy](https://romefrontend.dev/#technical), one of the goals of the project is to `Use inclusive terminology`. Since this project is a linter, it would be good to create linter rules for this, this way Rome code will be checked for inclusive terminology by itself.

**Comment by sesm** [comment]
Looks like it's already fixed in https://github.com/romefrontend/rome/pull/267, closing

**Comment by sebmck** [comment]
Note that it's currently disabled while we figure out a more sustainable approach to term management. ie. Non-English, custom words etc. See #793 for additional conversation.
