### ISSUE TITLE
🐛 parse/spdxLicense errors during rome init

### ISSUE THREAD

**Issue by ottob** [romefrontend/rome#1064]
## Environment

```
$ rome rage --summary
Environment Variables
  Object {
    TERM: "xterm-256color"
    TERM_PROGRAM: "Apple_Terminal"
  }

User Config
  unset

Rome Version
  10.0.4-beta

Node Version
  12.18.3

Platform
  darwin x64 19.6.0

Terminal Features
  Object {
    background: "unknown"
    colorDepth: 8
    columns: 82
    cursor: true
    hyperlinks: true
    isTTY: true
    unicode: true
  }

Client Flags
  Object {
    clientName: "cli"
    cwd: "/Users/myuser/dev/myoldproject"
    realCwd: "/Users/myuser/dev/myoldproject"
    silent: false
  }

Server Status
  Object {
    projects: Array [
      Object {id: 0}
      Object {id: 1}
    ]
    server: Object {
      heapTotal: 26_583_040
      pid: 7_661
      uptime: 0.265367234
    }
    workers: Array [
      Object {
        astCacheSize: 0
        heapTotal: 26_583_040
        ownedBytes: 0
        ownedFileCount: 0
        pid: 7_661
        uptime: 0.265289183
      }
    ]
  }


✨  Done in 0.56s.
```

## Steps To Reproduce

1. run `rome init` in existing project.
2. look at generated errors:
```
 Welcome to Rome! Let's get you started... 

[1/2] Generating .editorconfig

 node_modules/dom-storage/package.json:16:19 parse/spdxLicense ━━━━━━━━━━━━━━━━━━━

  ✖ Expected token ParenClose but got Word

 node_modules/xmldom/package.json:21:24 parse/spdxLicense ━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Expected token ParenClose but got Word

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✖ Found 2 problems
```

It seems like it fails to parse these licenses:
1. `(MIT or Apache-2.0)` from `dom-storage` 2.1.0 (latest) here https://git.coolaj86.com/coolaj86/dom-storage.js/src/branch/master/package.json#L16
1. `(LGPL-2.0 or MIT)` from `xmldom` version 0.1.31 here  https://github.com/xmldom/xmldom/blob/91e456310880c24ae97629bd5754f96ffcb623c5/package.json#L21

## Expected Results

No errors.

**Comment by sebmck** [comment]
I think it's because we require `or` and `and` in SPDX expressions to be capitalized.

**Comment by sebmck** [comment]
Yeah, we expect them to be capitalized. `tokenize` in `internal/codec-spdx-license/parse.ts` should be updated to also respect the lowercase form.

**Comment by nerdybeast** [comment]
I can repro this by simply doing `npx rome init`:
![image](https://user-images.githubusercontent.com/15707802/90421106-c0449a80-e06d-11ea-8fb7-dcaf0fbf3531.png)
