### ISSUE TITLE
📎 Perform bundle concatenation in test workers

### ISSUE THREAD

**Issue by sebmck** [romefrontend/rome#1067]
Right now tests are extremely slow because we ship a few megs of JS for each bundled test. We can just send over the unique files and concatenate them after. Will require some significant changes and abstractions to the bundler.

**Comment by ayshiff** [comment]
Can I work on this @sebmck ?

**Comment by sebmck** [comment]
@ayshiff This issue should have actually already been closed since we now do this, among some other bundle concat optimizations.
