### ISSUE TITLE
📎 Create a new project config where user can store invalid licenses 

### ISSUE THREAD

**Issue by ematipico** [romefrontend/rome#1075]
From https://github.com/romefrontend/rome/issues/1037#issuecomment-673377148
> We "lint" package.json files but it’s not really linting. We load, normalize, and validate any we see during project initialization since they’re required for module resolution.

> It has been an area of confusion though because you cannot ignore them because any validation errors are either legitimate problems or bugs/unhandled validation cases, and are fatal.

And from https://github.com/romefrontend/rome/issues/1037#issuecomment-673719698

> Probably a project config option to allow certain invalid licenses.

**Comment by ematipico** [comment]
I think I will start working on this and pause the markdown parser.

I believe this has more priority and it's stopping more and more people from using rome.

@sebmck did you have some idea in mind already?

We could have a top level config called `dependencies` and map the invalid licenses by package:

```js
// rome.rjson
dependencies: {
	licenses: {
		"Invalid License": ["dep1", "dep2"]
	}
}
```

We could fill these information at project `init`. Do we have this information already or do we have to run a specific function in order to retrieve information about the dependencies?

**Comment by sebmck** [comment]
I think we should have a general place to put "package exceptions", where people can explicitly list invalid packages. The `dependencies` field is a good idea, but I would go even further and have something like:

```
dependencies: {
    exceptions: {
        invalidLicenses: {
            "Invalid License": ["dependency-name@version"]
        }
    }
}
```

Then when we're presenting the license errors we can have a diagnostic that says:

```
To automatically add an exception for this license, run:

$ rome config push dependencies.exceptions.invalidLicenses.LICENSE_NAME "name@version"
```

**Comment by sebmck** [comment]
Relevant files that would need to be changed are `internal/project` to add the project config fields. You would need to pass the information to `codec-js-manifest` somehow, there's a few different ways you could try. Keep in mind for that specifically, that it can't take a single `ProjectConfig` object, as with nested projects we need to be able to support checking against multiple. Let me know if you need any more specific pointers, happy to help!
