### ISSUE TITLE
💭 add something like --disable-formatting

### ISSUE THREAD

**Issue by nles** [romefrontend/rome#1103]
I'm currently using Rome for a Next.js codebase (with TypeScript). It seems there's still some work to be done with getting JSX/TSX formatting rules up to speed with the best practices (https://github.com/romefrontend/rome/issues/341). I don't really care about things like single quotes vs double quotes, as long as there are some uniform practice in place. But things like the lack of `react/jsx-wrap-multilines` and others really make the Rome formatted JSX files less readable.

In them meanwhile, it would be great to get the benefit of Rome with the well thought out linting rules you support.

I thought something like `--disable-formatting` could be able to cover this use case really nicely. I could also run `rome check` without using `--apply` for kind of the same effect, but in that case the output is way too verbose to figure out what linting errors I have, since I'll also get all of the formatting errors from pretty much every JSX file (all under `lint/pendingFixes`).

As a workaround, I'm using `rome check --format-only; prettier --write . > /dev/null`. That's really unoptimal, since it changes every JSX file twice (first according to Rome rules, then according to Prettier rules), but the output is much more readable, since this outputs only the lint errors from Rome.

**Comment by ematipico** [comment]
PR open: https://github.com/romefrontend/rome/pull/1163

**Comment by sebmck** [comment]
You'll now be able to have `{format: {enabled: false}}` in your project config and formatting/autofixes will be disabled. You also will not get the autofix command suggestions.

**Comment by nl3s** [comment]
I'm trying to test this out, but it keeps failing with:

![image](https://user-images.githubusercontent.com/69427864/92381211-18256d00-f113-11ea-9ec6-5d46fcf84e22.png)

It seems that these changes have not gone out to the published version yet, so I tried running from the latest main branch (with no luck...)

Here's what I did to run `rome check` with a version from the main branch:
```
git clone https://github.com/romefrontend/rome
cd <rome-dir>
./rome ci --fix
cd <my-project>
./<rome-dir>/rome check
```

My .config/rome.rjson looks like this:
```
name: "myproject"
format: {
  enabled: false
}
lint: {
  ignore: [
    ".next"
  ]
}
root: true
```

**Comment by ematipico** [comment]
Hi @nl3s , unfortunately we haven't released this feature yet. At the moment we have an issue with the official documentation that gets updated straight from the `main` branch.

**Comment by ematipico** [comment]
Would you mind open an issue @nl3s ? I think I know what's the issue
