### ISSUE TITLE
💭 lint/ts/useInterfaces has incorrect documentation

### ISSUE THREAD

**Issue by antonk52** [romefrontend/rome#1130]
I've been reading about already implemented rules and found that [`ts/useInterfaces`](https://romefrontend.dev/docs/lint/rules/ts/useinterfaces/) rather confusing. It openly states that the rule is equivalent to [`jsx-filename-extension`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-filename-extension.md) which is about file extensions, not typescript interfaces as some may assume from the rule's name. From examples we can see that this rule also reports errors for files with `.js` extension containing jsx elements which is not about typescript(the rule is under `ts` rules). Can we please clarify the rule's name or move it outside of `ts` rules to avoid further confusion?

PS: amazing work 👍

**Comment by sebmck** [comment]
The docs are completely wrong and likely the result of a copy+paste error when I was working on them in the rush for our official release.

The rule is intended to lint against the usage of object type aliases. However, when enabling it I noticed some critical errors that prevent its adoption, at least in the Rome codebase itself.

It is not possible to match interfaces with static fields against another with a computed property. This basically makes it completely untenable for usage in JSON types.

The rule is currently a noop for this reason. I was hoping to get back to it and possibly utilize some smarter static analysis.

You can read more about this in the PR where the rule was added: #677
