### ISSUE TITLE
💭  Commands passed to `ast-create-node` are very confusing, it should be based on the file-structure

### ISSUE THREAD

**Issue by nordxai** [romefrontend/rome#1161]
Hi Rome team,

Was going through the Contribution doc and came across the [`ast-create-node`](https://github.com/romefrontend/rome/blob/main/CONTRIBUTING.md#ast-create-node) section and the commands passed down to the script are very confusing and are not based on the file structure of the `ast` folder.

Rather than `./rome run scripts/ast-create-node [language] [nodeType] [category]`

This might be better: `./rome run scripts/ast-create-node [language] [category] [nodeType]`

In terms of file structure, it would be like `ast/js(language)/typescript(category)/JSArrayType(nodeType)`

I believe the proposed command reorg would work really well with how the file is being generated.
What does the Rome team think?

**Comment by sebmck** [comment]
Sure, want to submit a PR? Those have grown organically, and there aren't any strong technical decisions or opinions behind any of the `scripts`.

Previously we never had separate language namespaces, we just had a `category`. When we added support for multiple languages I just renamed the `category` argument to `language` and added another `category` argument at the end.

Another approach is to just have a single argument that's `/` delimetered like:

```
scripts/ast-create-node ts/whatever/SomeNode
```

And we would just split and validate it. I believe we already do this for the delete ast script.

**Comment by nordxai** [comment]
> Sure, want to submit a PR?`.

Absolutely mate.

And I do like your approach on the arguments being delimited by `/` and form one command, just like the way [lint-create-rule](https://github.com/romefrontend/rome/blob/main/CONTRIBUTING.md#lint-create-rule) command works.
Will look into the delete ast script and of course, the lint-create-rule before writing my implementation.

Cheers

**Comment by nordxai** [comment]
Btw, I was already half way through the reimplementation of the aforementioned opened `issue` and found a bug on the current implementation of `ast-create-node` command.

The condition in question: https://github.com/romefrontend/rome/blob/4000dec37b06854b16e113a9c756905339c04c16/scripts/ast-create-node.ts#L25-L30
It looks like it's checking if the `filename` has a prefix of the `language` name and if not, you're given this error:


<img width="800" alt="Screen Shot 2020-08-31 at 7 13 04 pm" src="https://user-images.githubusercontent.com/54709525/91704431-f2521280-ebbe-11ea-834e-cd6366601a8b.png">

It requires `TSWow.ts` to have a `JS` prefix, which doesn't make sense since I'm creating a `TS` prefixed file.

A solution could be that we would create exceptions for some categories such as `jsx` and `typescript` to not be prefixed `language` or we could simply remove this condition, what do you all think @sebmck?

**Comment by nordxai** [comment]
> Btw, I was already half way through the reimplementation of the aforementioned opened `issue` and found a bug on the current implementation of `ast-create-node` command.
> 
> The condition in question:
> 
> https://github.com/romefrontend/rome/blob/4000dec37b06854b16e113a9c756905339c04c16/scripts/ast-create-node.ts#L25-L30
> 
> 
> It looks like it's checking if the `filename` has a prefix of the `language` name and if not, you're given this error:
> <img alt="Screen Shot 2020-08-31 at 7 13 04 pm" width="800" src="https://user-images.githubusercontent.com/54709525/91704431-f2521280-ebbe-11ea-834e-cd6366601a8b.png">
> 
> It requires `TSWow.ts` to have a `JS` prefix, which doesn't make sense since I'm creating a `TS` prefixed file.
> 
> A solution could be that we would create exceptions for some categories such as `jsx` and `typescript` to not be prefixed `language` or we could simply remove this condition, what do you all think @sebmck?

So I went ahead and added a `whitelistedPrefix` array and added `TS`(for now), so that we can have different prefixes other than the main language which in this case was `js` and our prefix was `TSSomeFile.ts`.
