### ISSUE TITLE
🐛 Incorrect heading level for `dependencies.exceptions.invalidLicenses`

### ISSUE THREAD

**Issue by sebmck** [romefrontend/rome#1162]
![Screen Shot 2020-08-30 at 3 11 10 PM](https://user-images.githubusercontent.com/853712/91670505-22bc8280-ead3-11ea-8249-19ea67a7e904.png)

It's too long and causes the sidebar to overflow

**Comment by ematipico** [comment]
yeah I had noticed that bug too and I forgot to open an issue.

What about the length of the wording? Maybe we should come up with a different wording in order to avoid these long names

**Comment by EduardoLopes** [comment]
Closing this because the issue is already fixed. But use different wording to avoid long names is a good idea.
