### ISSUE TITLE
☂️ Path to a published release

### ISSUE THREAD

**Issue by sebmck** [romefrontend/rome#413]
This issue is tracking the remaining tasks before we have an official release.

- [x] Transfer repo to [@romejs](https://github.com/romejs/) org

This will hopefully be done by the end of the work. There's some additional things to work out.

- [ ] Rework website

I'm handling this one. I want a mostly single-page website for 90% of people. Not single page as in SPA, single page as in a single page to scroll through.

Taking inspiration from classic projects such as [coffeescript.org](http://coffeescript.org/), [backbonejs.org](https://backbonejs.org/), and [underscorejs.org](https://underscorejs.org/).

I find the current structure of most open source projects to be extremely confusing. Someone should be able to spend 20 minutes reading through the Rome documentation and have a good grasp on how to use almost all of it (we'll see).

- [x] Add more tests

Tests are lacking in many areas. Notably `@romejs/core`.

- [x] <strike>Automated releases

After the initial release I want to be able to push new release really quickly. I am fine doing multiple releases a day. Patch and minor versions are cheap.

This means we need to invest in tooling to quickly publish releases. It should be semi-automated, just running a command or pushing to a branch should trigger a release.

**Comment by sebmck** [comment]
I don't think it makes sense to have blockers on pending features or missing lint rules.

**Comment by aarjithn** [comment]
Do we have any target on what the publish version should be capable of doing?

**Comment by sebmck** [comment]
Everything it does now. There's no other launch blockers besides a new website and additional tests.

**Comment by egoist** [comment]
> I want a mostly single-page website for 90% of people. Not single page as in SPA, single page as in a single page to scroll through.

I made a documentation tool for this: docup.now.sh, would love some feedback from you 🤔

**Comment by macovedj** [comment]
> I'm handling this one. I want a mostly single-page website for 90% of people. Not single page as in SPA, single page as in a single page to scroll through.
> 
> Taking inspiration from classic projects such as [coffeescript.org](http://coffeescript.org/), [backbonejs.org](https://backbonejs.org/), and [underscorejs.org](https://underscorejs.org/).
> 
> I find the current structure of most open source projects to be extremely confusing. Someone should be able to spend 20 minutes reading through the Rome documentation and have a good grasp on how to use almost all of it (we'll see).

Just a thought about clear docs.  It's hard to express how much I value the versioned docs I've seen in the elixir community (linked below for reference), and the impact that that has had on the community's ability to be welcoming to newcomers.  If it's something you're up for, I'd love to help make it happen.

https://hexdocs.pm/elixir/1.10.1/Kernel.html
<img width="160" alt="Screen Shot 2020-05-16 at 12 54 33 PM" src="https://user-images.githubusercontent.com/20097860/82125528-80bb9900-9774-11ea-8b4b-e196b6781914.png">

**Comment by diokey** [comment]
I'd like to help with adding tests

**Comment by sebmck** [comment]
We now have a publishing process. The only thing remaining for a release is an improved website. I've opened #496 to track. Tests would be really nice but aren't a blocker for an alpha/beta release. If anyone is interested feel free to go through the folders in `packages/@romejs` and find a package that looks interesting and write some unit tests. You can find `*.test.ts` files elsewhere as a reference.

**Comment by sebmck** [comment]
Going to close this since #14 is the only actual blocker.
