### ISSUE TITLE
Unicode characters are rendered as emoji on mobile website homepage preview

### ISSUE THREAD

**Issue by sebmck** [romefrontend/rome#720]
There’s probably some CSS properties we can use to disable this.

![image](https://user-images.githubusercontent.com/853712/86902942-81611380-c0c3-11ea-9eac-1510e9d310a9.png)

**Comment by paulomenezes** [comment]
I would like to fix this.

**Comment by sebmck** [comment]
@paulomenezes Go for it! Clone the repo and run the following commands to setup the website for development:

```
cd website
npm install
npm run start
```

You'll then get a URL in the terminal that you can open.

**Comment by paulomenezes** [comment]
I found that we can use `&#xFE0E;` right after the unicode to prevent this be rendered as an emoji, but I don't know if is the best solution because this image can be replaced in the future.
