### ISSUE TITLE
Move lint rule test cases into JSON file and automatically generate lint rule docs

### ISSUE THREAD

**Issue by sebmck** [romefrontend/rome#728]
From #726:

> > What are your thoughts on using the test cases for rules as the Valid and Invalid cases in the doc?
> 
> Ohhh this would be so good. I wonder if there's an easy way we can do this.
> 
> Easiest way will be to move the `valid`/`invalid` test cases into a `json` file. That might actually be nice? We can eliminate a lot of the test files that are just a bunch of boilerplate for a `testLint` call.
> 
> Maybe something like:
> 
> ```
> {
>   "lint-rule-name": {
>     "valid": [],
>     "invalid": [],
>   },
> }
> ```
> 
> That we can have in `packages/@romejs/compiler/lint/rules/tests.json`. Then we can have `packages/@romejs/compiler/lint/rules/index.test.ts` that just imports it and sets up the tests. Then we can generate a lot of the lint docs.

**Comment by sebmck** [comment]
cc @VictorHom and @ematipico

**Comment by ematipico** [comment]
Yeah that was one of my initial thoughts at the very beginning when I started tackling the lint rules.

It would be nice and we can automate lot of boilerplate and documentation at the same time.

Nice Idea!

The tests can be part of the documentation.

**Comment by ematipico** [comment]
There's one thing that concerns me: having one single `.json` file for all the rules of a single category could create a very big file. This could create issues in managing such a big file.

What if we decided to scaffold a `.json` file for each rule? `anchorHasContent.test.json` which will contain

```json
{
	"invalid": [],
	"valid": []
}
```

**Comment by sebmck** [comment]
@ematipico Individual files makes a lot of sense.

I've also opened #747 and #748 to add multi linestring support and the ability to convert an RJSON file to regular JSON. That would be most useful for this since you can import RJSON normally and for any generated files we can run the `rjson` command to convert them so we can read them from those scripts.

**Comment by ematipico** [comment]
I am going to start moving the files under `rules/js`

**Comment by sebmck** [comment]
Resolved by #728. I think there's a few remaining but we can either track those in another issue or just leave them for now. Thanks @ematipico!
