### ISSUE TITLE
Error on overlapping suppression comment categories

### ISSUE THREAD

**Issue by sebmck** [romefrontend/rome#729]
From the Discord https://discordapp.com/channels/678763474494423051/678763474930761739/730499884528173189:

> > wondering if you can help explain " Error on overlapping ignore categories. Nested etc." - curious if it's something I can help out on
> 
> @victorhom#5522 Basically we updated the `rome-disable` comment semantics so that it suppresses everything "after it". eg.
> 
> ```
> // rome-disable lint/js/camelcase
> const foo_bar = function() {
>     // This error is also suppressed
>     bar_foo;
> };
> 
> // But this is still an error
> bar_foo;
> ```
> 
> But if you have:
> 
> ```
> // rome-disable lint/js/camelcase
> const foo_bar = function() {
>     // rome-disable lint/js/camelcase
>     bar_foo;
> };
> ```
> 
> Then the nested suppression comment is pointless.
> 
> This should just be a matter of going over the `suppressions` and making sure there's no overlaping ranges for a category.
> 
> Relevant file would be `packages/@romefrontend/compiler/suppressions.ts`. It already does some validation and returns a `diagnostics` array so it should only need to be confined to that file.

**Comment by sebmck** [comment]
@VictorHom Feel free to assign yourself if you want to take this up.

**Comment by VictorHom** [comment]
I can take a look at this. so essentially if it overlaps, then there should be an error that it's not necessary for the nested (overlapping) suppression

**Comment by sebmck** [comment]
Yeah exactly.

**Comment by sebmck** [comment]
Something like this:

```
Redundant suppression comment

> // rome-disable lint/js/camelcase
> const foo_bar = function() {
>     // rome-disable lint/js/camelcase
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     bar_foo;
> };

This suppression is already handled by the comment defined here:

> // rome-disable lint/js/camelcase
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> const foo_bar = function() {
>     // rome-disable lint/js/camelcase
>     bar_foo;
> };
```
