### ISSUE TITLE
Add blog to website

### ISSUE THREAD

**Issue by sebmck** [romefrontend/rome#730]
I worked on the base of this in `website/src/posts` and `website/src/_includes/layouts/post.njk` but didn't get very far.

The blog will just be a place for us to post announcements, new releases, changelogs etc. Just long form content for the project.

**Comment by sebmck** [comment]
It'd be pretty cool if we could automatically link the most recent blog post on the top of the homepage too.

**Comment by sebmck** [comment]
@EduardoLopes Any thoughts on the design? If I get around to this I was just going to wing it and take a lot of hints from your docs design. I can't imagine we'd want something too fancy, just a stripped derivative of the docs layout.

**Comment by EduardoLopes** [comment]
yeah! let's use the same design and nothing too fancy. i'll open a PR and work on that
