### ISSUE TITLE
Markers not written for `rome check --collect-markers`

### ISSUE THREAD

**Issue by yassere** [romefrontend/rome#733]
Markers are only written when the `ServerQueryResponse` type is "SUCCESS" but the `check` command results in a response type of "DIAGNOSTICS" because `Linter#runSingle` always throws a `DiagnosticsPrinter`

## Steps To Reproduce

Run `./scripts/dev-rome check --collect-markers`

## Expected Results

Markers should be written to a `json` file.

**Comment by sebmck** [comment]
Let's add the `markers` prop to all the `ServerQueryResponse` objects. We can just have `ServerQueryResponseBase` and extend it.
