### ISSUE TITLE
Write some of (or all) the functionality in Rust

### ISSUE THREAD

**Issue by egilsster** [romefrontend/rome#742]
This may or may not be completely irresponsible, but the idea kept roaming in my head, so decided to post it.

I have been writing a teeny tiny bit of [Rust](https://www.rust-lang.org/) recently and have gotten quite enamored with the language and its properties — a big one being performance. I realize, most, if not all, of the contributors of the project as of today (thank you ❤️ ) are seasoned JS/TS developers. Maybe we can learn both. I currently work with JS/TS tooling.

On to the title of this post. How does it sound to write some of the functionality for the project in Rust? Is it possible to wire them in and they can be called from TypeScript and in then Rustify the worker?

What kind of triggered the idea was that we now have [`deno`](https://deno.land/). Very interesting project. `deno` contains some tooling around it and recently [`deno_lint`](https://github.com/denoland/deno_lint) made its debut and they show some performance numbers versus `eslint` which are impressive. It would be really nice to have some of that sweet Rust performance.

Maybe I am missing something super trivial that renders this completely blank. Maybe I get to help out making this real.

What do you think?

**Comment by sebmck** [comment]
Hey! I think your questions have already been answered in #144. Let me know if there's anything else I can answer!

**Comment by egilsster** [comment]
That plus the HN thread capture exactly what I was hoping to get. Appreciate the time, thanks!

**Comment by vjpr** [comment]
As of 2021/08/03, Rome is being [re-written in Rust](https://twitter.com/rometools/status/1422616144763097091?lang=en).
