### ISSUE TITLE
📎 `init` command improvements

### ISSUE THREAD

**Issue by sebmck** [romefrontend/rome#756]
`rome init` is going to be the first command a new Rome user runs. We should make it work well for existing codebases. We will probably want to make these improvements before our release:

- Automatically add `// @jsx` to .js files that contain JSX
- Automatically populate `lint.globals` with undeclared variables. There is a `meta` property on `Diagnostic` that we set in `lint/js/undeclaredVariables`. You can filter the diagnostics for that category name and extract the undeclared variables from there.
- Run `rome check --apply` to run formatting and add autofixes
- Maybe run `rome check --review` too so people can suppress other lint errors?
- Make an `.editorconfig` with `tab_style`

**Comment by ematipico** [comment]
@sebmck I might be able to help here.
Is there a specific order of how we want to run things?
