### ISSUE TITLE
Add `hidden` to non-lint commands. Warn when using a hidden command.

### ISSUE THREAD

**Issue by sebmck** [romefrontend/rome#757]
We should hide all non-lint related commands. These will technically work at launch but we shouldn't be advising people to use them as they are unpolished/probably non-functional commands. We should hide them from `--help` and have a warning. I'm pretty sure there's already a command `hidden` option that can be used to hide them from `--help`. We can add the warning to any hidden command executed by `cli-flags`.

**Comment by ematipico** [comment]
I would like to work on this one!
