### ISSUE TITLE
📎 Consistent lint rule naming

### ISSUE THREAD

**Issue by sebmck** [romefrontend/rome#758]
Right now the lint rule naming is inconsistent. We use `no` and `prefer` prefixes on different things. We should converge on a consistent naming scheme. This task is for renaming them, and if possible, figuring out some written guidelines for future lint rule names.

**Comment by bitpshr** [comment]
Happy to take this.

**Comment by bitpshr** [comment]
Just an update, I'm almost done the naming consolidation here.

**Comment by ematipico** [comment]
What will be the standard naming convention?

**Comment by bitpshr** [comment]
@ematipico apologies, I missed your comment. Check the pull request description at #965 for a convention overview. We can definitely tweak things going forward if any rules don't fit into the two rule categories described.
