### ISSUE TITLE
New lint rule: Disallow shouty constants that have the same variable name as the value

### ISSUE THREAD

**Issue by sebmck** [romefrontend/rome#761]
This is such a bad pattern:

```
const FOO = 'FOO';
```

It's typically used for constants. The prevailing consensus once you actually drill down into why people do this is for no good reason.

We can have an autofix to inline these (unless exported, which we should probably error on).

This should be _relatively_ easy.

 - For all `JSReferenceIdentifier`, look up the `scope.getBinding`. If it matches `binding instanceof ConstBinding && !binding.isExported` and you check the `binding.value` and it's a string literal, with the same value as the name, inline it.
  - Do the reverse and remove `VariableDeclarator` that matches the above heuristics (not exported etc).

(There may be some usages in Rome so I'm a hypocrite.)

**Comment by ooflorent** [comment]
I’ll work on this
