### ISSUE TITLE
New lint rule: No implicit boolean JSX attributes

### ISSUE THREAD

**Issue by sebmck** [romefrontend/rome#763]
Don't allow:

```
<foo bar />
```

Autofix it to:

```
<foo bar={true} />
```

The consensus from anyone I've spoken to on the React team or those involved with the creation of JSX is that this was a mistake. It's always clearer to have the explicit boolean value and it's confusing with the introduction of shorthand object properties.

**Comment by bitpshr** [comment]
I'll grab this one.
