### ISSUE TITLE
📎 New lint rule: Set selfClosing on `HTMLElement` and `JSXElement` with no children

### ISSUE THREAD

**Issue by sebmck** [romefrontend/rome#764]
Right now we have a `selfClosing` property on `HTMLElement` and `JSXElement`. When formatting any of those nodes we check if `node.selfClosing === true && node.children.length === 0`. So `selfClosing` is merely a hint.

We do this so that to retain the original closing status that the developer wrote. This way when you're writing code and you have format-on-save enabled, we don't mess with what you are probably going to eventually fill in later.

We can provide consistency, and avoid messing with the developer, by making it a lint rule with an autofix instead that is ran deliberately.

Heuristics:

```
(node.type === "JSXElement" || node.type === "HTMLElement") && !node.selfClosing && node.children.length === 0
```

And then just `addFixableDiagnostic` with `{...node, selfClosing: true`.

**Comment by bitpshr** [comment]
I'll grab this one.
