### ISSUE TITLE
📎 New lint rule: `.?` preference rule

### ISSUE THREAD

**Issue by sebmck** [romefrontend/rome#765]
There are likely certain patterns where we can recommend `.?` there are certainly a lot of places inside of Rome where we do a lot of `=== undefined` checks where this would be valuable.

```
if (foo !== undefined && foo.bar !== undefined) {}
```

Could be suggested as:

```
if (foo?.bar !== undefined) {}
```

We should preferably also have an autofix.

Does a lint rule like this already exist for ESLint that we can take inspiration from? (AKA copy their heuristics)

**Comment by vovictort** [comment]
ESLint does not have this rule implemented yet. Someone proposed the new lint rule on June 20th, and is working to add it as a new feature. The lint rule is proposed as "Prefer Optional Chaining".

https://github.com/eslint/eslint/issues/13430
