### ISSUE TITLE
Add errors for supression comment prefix typos

### ISSUE THREAD

**Issue by sebmck** [romefrontend/rome#768]
We use `rome-ignore` as a comment prefix to for suppressions. However other tools use `-disable` like `eslint-disable or even have a `@` prefix like `@ts-ignore`.

We should only actually `rome-ignore` to work., but error for common typos such as:

 - `rome-disable`
 - `@rome-ignore`
 - `@rome-disable`
 - Maybe others?

Relevant file: `packages/@romefrontend/compiler/suppressions.ts`

@VictorHom Maybe something you're interested in.

**Comment by VictorHom** [comment]
I can take a look at this 👍
