### ISSUE TITLE
Consider changing governance voting rules to be private

### ISSUE THREAD

**Issue by sebmck** [romefrontend/rome#770]
Right now the `GOVERNANCE.md` section for core contributor induction says this about voting:

> New core contributors will be decided based on a vote conducted in the #contributors-private Discord channel.

Upon further reflection, having the vote done in public can result in people not wanting to voice their dissent or disapproval.

Should we change this to instead require messaging a steward (only me right now) to place a vote? This should be for both yes and no. This also adds some anonymity if the vote fails.

**Comment by bitpshr** [comment]
I agree that votes should be made in private. I also think that the subjective aspect of messaging a steward vs. using a private voting bot adds a necessary human element.

**Comment by sebmck** [comment]
@romefrontend/core-contributors Anyone want to draft a PR? Final decision/approval can be made there.
