### ISSUE TITLE
📎 Add safe array element get to Consumer

### ISSUE THREAD

**Issue by sebmck** [romefrontend/rome#776]
- Turn `asArray` into `asList` that returns an `Iterable` to prevent index lookup
- Add `getIndex`

**Comment by sebmck** [comment]
Actually this isn't necessary at all since you can just use `get("0")`... cc @yassere if you want to include that change in a future LSP PR.

**Comment by yassere** [comment]
Calling `get("0")` on a consumer-wrapped array doesn't currently work because of the internal call to `isPlainObject`

Should we add a `getIndex` method or modify `get`?

**Comment by sebmck** [comment]
Ah yeah, that makes sense. We should have a separate method since we can use `getIndex` as a hint that it should be an array and have a more specific error rather than a cryptic "expected an object".
