### ISSUE TITLE
Mirror LSP logs to Server Logger

### ISSUE THREAD

**Issue by sebmck** [romefrontend/rome#777]
Right now we have a `logMessage` method on `LSPServer`. We should also emit those logs to `this.server.logger.info`.

That way they're visible when running `rome logs` or `rome <command> --logs`. We also have the command `rome rage` and `rome <command> --rage` that will create a tarball with a lot of environment information, including the logs for a certain command execution that will be amazing for debugging bugs that are reported.

cc @yassere you might be interested. Small one-line change.

**Comment by sebmck** [comment]
I think I made it do this already

**Comment by yassere** [comment]
Great! Thanks for the fixing the lsp `--logs` crashes in #791
