### ISSUE TITLE
Randomize team member order on website team page

### ISSUE THREAD

**Issue by sebmck** [romefrontend/rome#795]
`ul.team-list` in `website/src/contributing/team.md` should be randomized on load. We can do this with simple JS magic that can be added to `website/static/js/index.js`.

**Comment by aravind1078** [comment]
can i take this up ?

**Comment by ematipico** [comment]
@aravind1078 feel free to go ahead!

**Comment by sebmck** [comment]
Closed by #810. Thank you @aravind1078!
