### ISSUE TITLE
🐛 Running `init` command to a project already initialised goes in heap out of memory

### ISSUE THREAD

**Issue by ematipico** [romefrontend/rome#801]
Description:

Calling the command `rome init` (`scripts/dev-rom init`) on a project that already has a `rome.rjson` file, create a heap out of memory. 

Not sure if this is a problem related to the `dev-rome` script or not.

<img width="1643" alt="Screenshot 2020-07-14 at 08 24 07" src="https://user-images.githubusercontent.com/602478/87396891-70287300-c5ab-11ea-8228-50c16687c107.png">

## Steps To Reproduce

1. run the command `rome init` 
2. make sure that the command creates the fine `rome.json`
3. run the command `rome init`

## Expected Results

The program should not break and say that the project is already `init`'ed.

**Comment by ematipico** [comment]
After further investigation, I noticed that this heap of memory occurs every time that we run a command and the script start to build the project.

```
(node:32039) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'stdio' of undefined
    at Object.exports.exec (/Users/emanuele/www/rome/scripts/_utils.cjs:43:12)
    at Object.exports.execNode (/Users/emanuele/www/rome/scripts/_utils.cjs:52:17)
    at Object.exports.execVendor (/Users/emanuele/www/rome/scripts/_utils.cjs:132:17)
    at Object.exports.buildTrunk (/Users/emanuele/www/rome/scripts/_utils.cjs:164:10)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async exports.execDev (/Users/emanuele/www/rome/scripts/_utils.cjs:114:2)

```

**Comment by sebmck** [comment]
Does this still repro?

**Comment by ematipico** [comment]
@sebmck Now I can't even generate the `rome.rjson` file anymore. I tried to remove the `"rome":` object from the `package.json` and and when I run `./rome init` I get:

<img width="963" alt="Screenshot 2020-08-07 at 08 51 43" src="https://user-images.githubusercontent.com/602478/89622635-3df8f100-d88b-11ea-81c0-7664e626961b.png">
