### ISSUE TITLE
📎 Syntax highlighting of RJSON in VSCode extension

### ISSUE THREAD

**Issue by ematipico** [romefrontend/rome#805]
Now that we internally use `.rjson` files extensively, we could extend the VSCode extension to detect these files and highlight its syntax.

I would be also great if we could apply the linting too

**Comment by sebmck** [comment]
Not sure how these are declared in an extension but might be reasonably "straight forward". We can likely copy existing JSON grammar since our data types/syntax are copied and quite basic.
