### ISSUE TITLE
Missing description for commands flags

### ISSUE THREAD

**Issue by ematipico** [romefrontend/rome#809]
Description:

Missing description for flags that belong to a command

## Steps To Reproduce
1. run `scripts/dev-rome check --help`
2. check result

<img width="398" alt="Screenshot 2020-07-14 at 15 21 41" src="https://user-images.githubusercontent.com/602478/87437062-bdc1d180-c5e5-11ea-9c00-54d2119b9d12.png">

## Expected Results

There should be a description to explain the option

**Comment by sebmck** [comment]
The 'get' method on 'Consumer' that's used for all the CLI flags accepts an additional object parameter that can include a description prop, which will then be visible in '--help'.
