### ISSUE TITLE
📎 Add `rome cache` command

### ISSUE THREAD

**Issue by sebmck** [romefrontend/rome#828]
We'd probably only want one subcommand, `rome cache clean`. We might run into cache poisoning issues so it would be nice to have a command we can tell people to run to potentially fix it. This is low maintenance since it's a single delete call.

**Comment by bitpshr** [comment]
Note that `rome cache clear` already exists, along with `rome cache dir`. Do we still need this issue?

**Comment by sebmck** [comment]
Nope! Thanks for the reminder!
