### ISSUE TITLE
📎 Make better icons for mobile topbar

### ISSUE THREAD

**Issue by EduardoLopes** [romefrontend/rome#857]
- [x] show a close icon when the menu or TOC is open on mobile

Current: 
![Annotation 2020-07-20 002545](https://user-images.githubusercontent.com/1084297/87912471-d4cc4d80-ca43-11ea-97ea-83e142552f33.png)

Others interations:
![Annotation 2020-07-19 214838](https://user-images.githubusercontent.com/1084297/87912473-d5fd7a80-ca43-11ea-8aea-fa2a1f5c050a.png)
![Annotation 2020-07-19 214934](https://user-images.githubusercontent.com/1084297/87912474-d5fd7a80-ca43-11ea-9de1-cb318bfcdd8d.png)
![Annotation 2020-07-19 225536](https://user-images.githubusercontent.com/1084297/87912475-d6961100-ca43-11ea-93f4-60ad6dc142f9.png)
![Annotation 2020-07-19 225635](https://user-images.githubusercontent.com/1084297/87912477-d6961100-ca43-11ea-9041-7b3639c2d20c.png)
![Annotation 2020-07-19 231510](https://user-images.githubusercontent.com/1084297/87912479-d72ea780-ca43-11ea-8abe-747a1fc4855d.png)

**Comment by sebmck** [comment]
For posterity, I think the clearest thing we can do here is make it a magnifying icon and move/copy the search input into the table of contents pane. It groups index/searching behind a single button.

**Comment by EduardoLopes** [comment]
Yea, that's the best idea so far!

I think it's better to have an input for desktop, and another one for mobile. So on desktop we keep the search input on the left side bar, and doesn't have to show the right side bar when there's no TOC in the page. I'll look into it!
