### ISSUE TITLE
🐛 LSP Server crashing on files in non-Rome projects

### ISSUE THREAD

**Issue by yassere** [romefrontend/rome#885]
## Steps To Reproduce

Run `./rome run scripts/run-vscode-extension.ts`
Open a file in a non-Rome project.

## Expected Results

Rome should not crash.

**Comment by sebmck** [comment]
What's the error?

**Comment by yassere** [comment]
I think we just need to check `findProjectExisting` in a few more spots before calling a `ServerRequest` method. I just opened this issue as a reminder to take care of it this weekend.
