### ISSUE TITLE
🐛 Overlapping terminal output

### ISSUE THREAD

**Issue by yassere** [romefrontend/rome#888]
## Environment

<details>
<summary> $ rome rage --summary</summary>

```
Environment Variables
  Object {
    COLORTERM: "truecolor"
    LANG: "en_US.UTF-8"
    PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Yasser/bin:/Users/Yasser/bin"
    TERM: "xterm-256color"
    TERM_PROGRAM: "vscode"
    USER: "Yasser"
  }

User Config
  unset

Rome Version
  0.0.26-dev

Node Version
  14.6.0

Platform
  darwin x64 19.5.0

Terminal Features
  Object {
    background: "unknown"
    colorDepth: 24
    columns: 142
    cursor: true
    hyperlinks: true
    isTTY: true
    unicode: true
  }

Client Flags
  Object {
    clientName: "cli"
    cwd: "/Users/Yasser/Dev/rome"
    silent: false
  }
```
</details>

## Steps To Reproduce

Run `./rome check`

<img width="245" alt="Screen Shot 2020-07-25 at 8 55 20 AM" src="https://user-images.githubusercontent.com/7271639/88458647-28300880-ce55-11ea-8693-6cdf815ef0bb.png">

## Expected Results

Old lines should be fully cleared.

**Comment by ematipico** [comment]
I have the same issue

**Comment by sebmck** [comment]
Are you both using the VSCode terminal?

**Comment by sebmck** [comment]
There's some weirdness going on with other terminal emulators and cursor movement.

**Comment by sebmck** [comment]
Fixed it. Working on regression tests and other tests for the ANSI cursor movement and will have a PR up soon.
