### ISSUE TITLE
📎 Verify generated file contents for an actual hash match rather than just the comment

### ISSUE THREAD

**Issue by sebmck** [romefrontend/rome#906]
From #904: 

> Ahhh I totally missed this! Our generated files utils don't actually check the validity of the content after the hash comment, and just checks the hash of what we should have inserted. I'll open an issue to track adding that.

**Comment by ematipico** [comment]
Closed by #904

**Comment by sebmck** [comment]
Sorry, that's not in mind what I meant for this issue. In `readGeneratedFile` @ `scripts/_utils.ts` we should hash everything after the comment in the file and make sure it also matches the `currentHash`.

**Comment by ematipico** [comment]
Ok that makes sense then :)

Should we apply the logic to all the auto generated files?

**Comment by sebmck** [comment]
Yeah, that method is used for reading all generated so only handling it there will make it work everywhere.

**Comment by sebmck** [comment]
Did this already.
