### ISSUE TITLE
📎 Automatically pull website intro from README

### ISSUE THREAD

**Issue by sebmck** [romefrontend/rome#908]
We should be able to do this fairly easy by adding something to eleventy. We'll just have to replace the absolute paths with something relative (just stripping the hostname should be enough).

**Comment by nordxai** [comment]
I believe this issue has been mitigated in #930, correct me if I'm wrong @sebmck? If correct, then it should be closed.

**Comment by ematipico** [comment]
I think the idea was to do it automatically, which means updating the README file would be reflected to the website too. At the  it would be a manual process

**Comment by sebmck** [comment]
Yeah this has been resolved. They are now both synced with a generation script and will error in CI if they aren't. Thanks for raising @nordxai!
