### ISSUE TITLE
🐛 Decisions applying unrelated autofixes

### ISSUE THREAD

**Issue by yassere** [romefrontend/rome#922]
## Environment

<details>
<summary>$ rome rage --summary</summary>

```
Environment Variables
  Object {
    COLORTERM: "truecolor"
    LANG: "en_US.UTF-8"
    PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Yasser/bin:/Users/Yasser/bin"
    TERM: "xterm-256color"
    TERM_PROGRAM: "vscode"
    USER: "Yasser"
  }

User Config
  unset

Rome Version
  0.0.26-dev

Node Version
  14.6.0

Platform
  darwin x64 19.5.0

Terminal Features
  Object {
    background: "unknown"
    colorDepth: 24
    columns: 157
    cursor: true
    hyperlinks: true
    isTTY: true
    unicode: true
  }

Client Flags
  Object {
    clientName: "cli"
    cwd: "/Users/Yasser/Dev/rome"
    realCwd: "/Users/Yasser/Dev/rome"
    silent: false
  }
```
</details>

## Steps To Reproduce

With a file `foo.ts` as:
```js
let bar;
const foo = () => {};
```
Running `./rome check foo.ts --decisions suppress-lint/js/noUnusedVariables-foo.ts-1` results in:
```js
// rome-ignore lint/js/noUnusedVariables
let bar;
function foo() {}
```

## Expected Results

It should add the suppression comment without autofixing the const function.

**Comment by sebmck** [comment]
This was actually only isolated to that particular lint rule. Fixed in 857d8b91cb2408c3fc76d6af93d9a588abd88512. There was even a TODO that it ignored suppressions that I forgot about...
