### ISSUE TITLE
📎 [docs] add description to our rules

### ISSUE THREAD

**Issue by ematipico** [romefrontend/rome#939]
At the moment our rules page (https://romefrontend.dev/docs/lint/rules/?veryfunny) is quite empty and we should make an effort to put some documentation.

How to help:
- open a rule file (e.g. `preferInterfaces.md`)
- update the `description: MISSING DOCUMENTATION` part. This will update the brief description inside the main rules page
- update the `MISSING DOCUMENTATION` under the name of the rule with some meaningful description; alternately we can have a link to the upstream rule at the moment. We don't need some fancy stuff I think :)
- run the command `./rome run scripts/generate-all-files.ts` and commit everything

I will start with some PR

**Comment by katungi** [comment]
Hey @ematipico I would like to help out on this with your guidance.

**Comment by ematipico** [comment]
Hey @katungi, thank you for that! 

You could start with some rule that you might be comfortable with and follow this PR https://github.com/romefrontend/rome/pull/941 as example! If possible, for now, it's preferable to avoid rules that have names that start with "no" or "prefer", this is because we are in the process of applying some consistency to the name of the rules (see this https://github.com/romefrontend/rome/issues/758); this way, the risk of conflicts will be low.

If you have any questions, you can open a PR and continue the conversation there!
