### ISSUE TITLE
🐛  rome-initialization fails in node_modules 

### ISSUE THREAD

**Issue by aravind1078** [romefrontend/rome#956]
## Environment

```
$ rome init

```

## Steps To Reproduce

1.in an nextjs project install rome
2.run `rome init`
then it fails with error like below
![Screenshot 2020-08-08 at 9 47 49 AM](https://user-images.githubusercontent.com/22080780/89702316-c8118a00-d95d-11ea-9266-743e8031c0b6.png)

## Expected Results
it should initialize successfully

**Comment by sebmck** [comment]
Fixed by #957. Thanks for the report!
