### ISSUE TITLE
💭 Consider mandatory lint suppression explanations

### ISSUE THREAD

**Issue by sebmck** [romefrontend/rome#972]

**Comment by bitpshr** [comment]
If I understand this issue correctly, Rome would require suppression comments to include an explanation. I'm in favor of this; this wouldn't be too tedious during development where rules may be hastily turned off since a simple `"wip"` comment could be used until release.

**Comment by yassere** [comment]
How would this interact with `decisions` that add suppression comments? Would they insert a placeholder explanation or would they insert incomplete suppressions that need to be manually corrected?

**Comment by sebmck** [comment]
@yassere Probably a default explanation of "suppressed via --review" when run via the CLI. In LSP we could just have "insert explanation here" or something. There's probably also something cool that could be done with `--review` where you could write the explanation there. A CLI flag would also be nice to skip having to input it completely. eg.

```
rome review --suppression-explanation "Upgrading to Rome 10.0.6-beta"
```
