### ISSUE TITLE
📎 Warn if there are multiple configs

### ISSUE THREAD

**Issue by sebmck** [romefrontend/rome#979]
Currently if you have a `.config/rome.json` and `.config/rome.rjson` file, we wont complain and just use the first one we find.

**Comment by ayshiff** [comment]
Can I work on it @sebmck ?

**Comment by sebmck** [comment]
@ayshiff Sure! If you'd like!

Changes just need to be confined to the `findProject` method in `internal/core/server/project/ProjectManager.ts`. In the first loop we walk up the directory chain and search each directory for a config. Right now we bail as soon as we find one. What you'd have to do is defer the actual loading. You would need to:

 - Add a `foundProjectDirectory` variable that we assign when we've found a project folder.
 - When we find a project but the `foundProjectDirectory` variable has been set, throw an error (this should actually be a diagnostic, but if/when you submit a PR I can explain more about how to do that instead)
 - Moving the `watch` and `assertProjectExisting` calls to the bottom of the loop and do it on `foundProjectDirectory` if set.

Let me know if you have any questions or need clarification!
