### ISSUE TITLE
💭 Add ZSH shell completions

### ISSUE THREAD

**Issue by noftaly** [romefrontend/rome#993]
With rome we can enable shell completions with a simple command. It would be great if the ZSH shell was supported as it is widely used (it is the macOS' default shell).

If this can help, this article seems really helpful: https://mads-hartmann.com/2017/08/06/writing-zsh-completion-scripts.html

Thanks :)

**Comment by sebmck** [comment]
Sure! Want to submit a PR? Only file that needs to be changed is `internal/cli-flags/Parser.ts` and the following changes would be required:

 - Add `"zsh"` to `SupportedCompletionShells`.
 - Add `"zsh"` to the allowed values of the `shell-completions` flags in `init`.
 - Add a zsh branch to `writeShellCompletions` with logic on how to add it to a zsh profile.
 - Create `genZshCompletions` method and add it to `generateShellCompletions`.

**Comment by noftaly** [comment]
Thanks for these details! I'm not currently at home but I will try to make a PR! I don't promise anything 😄

**Comment by ematipico** [comment]
It's been here for a while now, I'll take a stab a it!
