### ISSUE TITLE
📎 Remove PATH from rage —summary

### ISSUE THREAD

**Issue by sebmck** [romefrontend/rome#995]
It's not really useful and can expose potentially sensitive information.

**Comment by ematipico** [comment]
I'd like to propose to remove the user too, if possible

**Comment by sebmck** [comment]
Sure. The only relevant information we need there is if they're running as ROOT, which can be a separate property. Want to make the changes? Client#generateRageSummary should be the only place.

**Comment by ematipico** [comment]
Sure, will do
