### ISSUE TITLE
💭 Consider supporting deno.

### ISSUE THREAD

**Issue by a1russell** [romefrontend/rome#997]
Rather than installing this via npm or yarn, I believe deno should be the first-class installation method. It'd be more forward-thinking, I think, to write against deno, another "reboot" by an influential author, and it would help differentiate from the current Babel/Webpack/ESLint toolchain. I believe this should be achievable especially since you are aiming for zero dependencies, and the project is still very young.

**Comment by Soremwar** [comment]
Deno already has its own built in tools to deal with these issues. If anything, feels like an unnecessary addition considering the idea would be too make the experience simpler to use.

**Comment by a1russell** [comment]
I know I closed this, but I wanted to add for posterity that deno bundle isn't currently intended for browsers:

> `deno bundle` is for running code in Deno.

https://github.com/denoland/deno/issues/6516#issuecomment-650756464

Other features like linting would still be a clash, though.
