### ISSUE TITLE
🐛 Errors thrown with `ci` and `test`

### ISSUE THREAD

**Issue by estevanmaito** [romefrontend/rome#999]
I commited and pushed somes fixes to my local fork and before PR, I realized I forgot to run the tests and recommended scripts, so I went back and tried to run the commands below (Steps To Reproduce).

The code to reproduce is present in this PR: #1000 

I only changed 3 `.md` documentation files.

## Environment

```
$ ./rome rage --summary
Environment Variables
  Object {
    COLORTERM: "truecolor"
    LANG: "en_US.UTF-8"
    PATH: <REDACTED>
    TERM: "cygwin"
    TERM_PROGRAM: "vscode"
  }

User Config
  unset

Rome Version
  10.0.3-beta-dev

Node Version
  14.2.0

Platform
  win32 x64 10.0.18362

Terminal Features
  Object {
    background: "unknown"
    colorDepth: 24
    columns: 165
    cursor: true
    hyperlinks: true
    isTTY: true
    unicode: false
  }

Client Flags
  Object {
    clientName: "cli"
    cwd: "D:\\rome"
    realCwd: "D:\\rome"
    silent: false
  }

Server Status
  Object {
    projects: Array [
      Object {id: 0}
      Object {id: 1}
    ]
    server: Object {
      heapTotal: 26_079_232
      pid: 12_212
      uptime: 0.202068001
    }
    workers: Array [
      Object {
        astCacheSize: 0
        heapTotal: 26_079_232
        ownedBytes: 0
        ownedFileCount: 0
        pid: 12_212
        uptime: 0.202001901
      }
    ]
  }
```

## Steps To Reproduce

1. `./rome ci`
2. `./rome ci --fix`
3. `./rome test`

## Expected Results

Running without errors.

## Error with `./rome ci`

https://gist.github.com/estevanmaito/5ae59e3d01d21c1720e1ac7d41b94439

## Error with `./rome ci --fix`

https://gist.github.com/estevanmaito/6afabc143ee8dbf9ab4b769aace0c24b

### Modified files

![changed](https://user-images.githubusercontent.com/8527573/89722915-d09dab00-d9c5-11ea-8f57-c9be7f40e4c5.png)

These files were modified after running `./rome ci --fix` (the same files are modified with `./rome check --apply`, but no error is thrown).

Apparently, `.rjson` files got 2 or 3 blank lines after comments:

`useClosingNonVoid.test.rjson` resulted in:

```json
filename: "filename.html"
invalid: [
	// "<div />"


]
valid: [
	"<div></div>"
	"<div>child</div>"
	"<input>"
	"<input />"
]

```

While `.json` got 2 blank lines added after _every_ line. eg. `error.json` 👇

https://gist.github.com/estevanmaito/269f077a983add29cd047e580d7f5828

## Error with `./rome test`

https://gist.github.com/estevanmaito/35b2f1bed41995cb4bec7ae2174b1eaf

Edit: added link to PR

**Comment by sebmck** [comment]
Huh, I'm not sure what could cause this. The out of memory error sometimes happens when there's a lot of test failures (causing us to read in a lot of source maps for the failed tests). Something might have broken in a previous run that just caused cascading problems.

**Comment by estevanmaito** [comment]
This commit apparently solved it for the PR https://github.com/romefrontend/rome/pull/1000/commits/a3b140db41abeb9978a949d6e3ba266ac1b95913

Looks like it has something to do with the linter, but the error is not exactly specified 🤔

**Comment by ematipico** [comment]
@estevanmaito do you still have this issue? Can it be closed?

**Comment by estevanmaito** [comment]
No, I think it was related to the spacing in .md files, as fixing spacing solved the problem.

I still have a related problem with https://github.com/romefrontend/rome/issues/1065 which prevents me from contributing with anything that's not documentation :(
